#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#███████████████████████████████████████████████████████████████████████████████
#███████████████████████████████████████████████████████████████████████████████
#███████████████████████████████████████████████████████████████████████████████
#███████████████████████████████████████████████████████████████████████████████
#███████████████████████████████████████████████████████████████████████████████
#███████████████████████████████████████████████████████████████████████████████
#└└└└└└└└└└└└└└└└└└└└└└└└└└└└└└└└║█████████████└└└└└└└└└└└└└└└└└└└└└└└└└└└└└└└└└
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ║████████████▌
#                                ╙▀▀▀▀▀▀▀▀▀▀▀▀▀


language: csharp
solution: Engine3D.sln