language: csharp
solution: Engine3D.sln
script:
  - msbuild /p:Configuration=Release Engine3D.sln
  - dotnet restore
  - dotnet test
  - msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
  - $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
##mono: latest
#mono: none
install:
  - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https
  - sudo apt-get update
  - sudo apt-get install -y dotnet-sdk-3.1

#script:
# - dotnet restore
# - dotnet build

#install:
#  - nuget restore Engine3D.sln
#  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
#  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
#script:
#  - msbuild /t:Restore
#  - msbuild /p:Configuration=Release