language: csharp
solution: Engine3D.sln
mono:
  - latest
  - 3.12.0
  - 3.10.0
os: windows
install:
  - sudo apt-get install nunit-console
  - nuget restore ./Engine3D.sln

script:
  - xbuild ./Engine3D.sln
  - nunit-console ./Engine3D/bin/Release/Engine3D.exe